name: Build (dev)

on:
  push:
    branches:
      - dev
permissions:
  contents: read

env:
  RUN_UNIT_TEST: "true"
  RUN_SAST: "true"
  RUN_SCA: "true"
  RUN_DAST: "true"

jobs:
  initialization:
    runs-on: ubuntu-latest
    outputs:
      envvalue1: ${{ steps.setvar.outputs.envvar1 }}
      envvalue2: ${{ steps.setvar.outputs.envvar2 }}
      envvalue3: ${{ steps.setvar.outputs.envvar3 }}
      envvalue4: ${{ steps.setvar.outputs.envvar4 }}
      dev_version: ${{ steps.versions.outputs.dev_version }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          sparse-checkout: .github/variables
          sparse-checkout-cone-mode: false
      - name: set value
        id: setvar
        run: |
          echo "envvar1=$RUN_UNIT_TEST" >> "$GITHUB_OUTPUT"
          echo "envvar2=$RUN_SAST" >> "$GITHUB_OUTPUT"
          echo "envvar3=$RUN_SCA" >> "$GITHUB_OUTPUT"
          echo "envvar4=$RUN_DAST" >> "$GITHUB_OUTPUT"
      - name: Load versions
        id: versions
        run: |
          source .github/variables/versions.env
          echo "dev_version=${DEV_VERSION}" >> "$GITHUB_OUTPUT"

  test-job:
    if: ${{ needs.initialization.outputs.envvalue1=='true' }}
    uses: SELISEdigitalplatforms/blocks-inventory/.github/workflows/1_unit_test.yml@main
    permissions:
      contents: read
      checks: write
      issues: write
      pull-requests: write
    with:
      COMMENT_RESULTS: false
    needs: [initialization]

  sast-job:
    if: ${{ success() && needs.initialization.outputs.envvalue2=='true' }}
    uses: SELISEdigitalplatforms/blocks-inventory/.github/workflows/2_sast.yml@main
    permissions:
      contents: read
      checks: write
      pull-requests: read
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_GLOBAL }}
      SONAR_GET: ${{ secrets.SONAR_GET }}
    needs: [initialization]

  sca-job:
    if: ${{ success() && needs.initialization.outputs.envvalue3=='true' }}
    uses: SELISEdigitalplatforms/blocks-inventory/.github/workflows/3_sca.yml@main
    permissions:
      contents: read
    secrets:
      DEPENDENCY_TRACK_API_KEY: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
    needs: [initialization]

  cd-job-build:
    if: ${{ github.event_name == 'push' && (needs.test-job.result == 'success' || needs.test-job.result == 'skipped') && (needs.sast-job.result == 'success' || needs.sast-job.result == 'skipped') && (needs.sca-job.result == 'success' || needs.sca-job.result == 'skipped') }}
    uses: SELISEdigitalplatforms/blocks-inventory/.github/workflows/api.yml@main
    permissions:
      contents: write
      id-token: write
    with:
      MODE: dev
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      BLOCKSOS_REPO: ${{ secrets.BLOCKSOS_REPO }}
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
    needs: [initialization]

  cd-job-worker-build:
    if: ${{ github.event_name == 'push' && (needs.test-job.result == 'success' || needs.test-job.result == 'skipped') && (needs.sast-job.result == 'success' || needs.sast-job.result == 'skipped') && (needs.sca-job.result == 'success' || needs.sca-job.result == 'skipped') }}
    uses: SELISEdigitalplatforms/blocks-inventory/.github/workflows/worker.yml@main
    permissions:
      contents: write
      id-token: write
    with:
      MODE: dev
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      BLOCKSOS_REPO: ${{ secrets.BLOCKSOS_REPO }}
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
    needs: [initialization]

  gitops-api-dev:
    uses: ./.github/workflows/update-gitops.yml
    permissions:
      contents: write
    with:
      SERVICE_NAME: blocks-localization-net
      SERVICE_TYPE: api
      ENVIRONMENT: dev
      IMAGE_TAG: ${{ needs.cd-job-build.outputs.image_tag }}
      VERSION: ${{ needs.initialization.outputs.dev_version }}
      CLUSTER_NAME: aks-blocks-dev
    secrets:
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
      BLOCKSOS_REPO: ${{ secrets.BLOCKSOS_REPO }}
    needs: [initialization, cd-job-build]

  gitops-api-nonprod:
    uses: ./.github/workflows/update-gitops.yml
    permissions:
      contents: write
    with:
      SERVICE_NAME: blocks-localization-net
      SERVICE_TYPE: api
      ENVIRONMENT: dev
      IMAGE_TAG: ${{ needs.cd-job-build.outputs.image_tag }}
      VERSION: ${{ needs.initialization.outputs.dev_version }}
      CLUSTER_NAME: aks-blocks-dev-nonprod
    secrets:
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
      BLOCKSOS_REPO: ${{ secrets.BLOCKSOS_REPO }}
    needs: [initialization, cd-job-build]

  gitops-worker-dev:
    uses: ./.github/workflows/update-gitops.yml
    permissions:
      contents: write
    with:
      SERVICE_NAME: blocks-localization-net
      SERVICE_TYPE: worker
      ENVIRONMENT: dev
      IMAGE_TAG: ${{ needs.cd-job-worker-build.outputs.image_tag }}
      CLUSTER_NAME: aks-blocks-dev
    secrets:
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
      BLOCKSOS_REPO: ${{ secrets.BLOCKSOS_REPO }}
    needs: [cd-job-worker-build]

  gitops-worker-nonprod:
    uses: ./.github/workflows/update-gitops.yml
    permissions:
      contents: write
    with:
      SERVICE_NAME: blocks-localization-net
      SERVICE_TYPE: worker
      ENVIRONMENT: dev
      IMAGE_TAG: ${{ needs.cd-job-worker-build.outputs.image_tag }}
      CLUSTER_NAME: aks-blocks-dev-nonprod
    secrets:
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
      BLOCKSOS_REPO: ${{ secrets.BLOCKSOS_REPO }}
    needs: [cd-job-worker-build]

  dast-job:
    if: ${{ github.event_name == 'push' && (success() || needs.initialization.outputs.envvalue4=='true') }}
    uses: SELISEdigitalplatforms/blocks-inventory/.github/workflows/4_dast.yml@main
    secrets:
      ZAP_API_KEY: ${{ secrets.ZAP_KEY }}
      ZAP_DASHBOARD_TOKEN: ${{ secrets.ZAP_DASHBOARD_TOKEN }}
    needs: [cd-job-build]l
